server:
  port: 9700
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gbiap?tinyInt1isBit=false&characterEncoding=GBK
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.benson.mybatis.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true