server:
  port: 9200

spring:
  application:
    # 设置应用名称
    name: eureka-server

eureka:
  instance:
    hostname: eureka-server2
    # prefer-ip-address: true
  client:
    # 单点服务注册中心配置以下两个配成false，高可用集群配置成true
    registerWithEureka: true
    fetchRegistry: true
    # Eureka Server的服务URL地址
    serviceUrl:
      defaultZone: http://eureka-server1:9100/eureka/,http://eureka-server3:9300/eureka/