server:
  port: 9001

spring:
  application:
    # 设置应用名称
    name: eureka-server1

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    # Eureka Server的服务URL地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/