server:
  port: 9600

spring:
  application:
    name: config-server
  profiles:
    active: jdbc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iot?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 111111
    type: com.alibaba.druid.pool.DruidDataSource
spring.cloud.config.server.jdbc.sql: SELECT config_key,config_value FROM config_center where APPLICATION=? and PROFILE=? and LABEL=?

#spring:
#  application:
#    name: config-server
#  profiles:
#    active: native # 加载本地配置
#  cloud:
#    config:
#      # 配置从git还是本地加载配置，二者选其一(git和native)
#      server:
#        #git:
#          # git仓库地址
#          #uri:
#          # git仓库下的相对目录，可以配置多个，用“，”分割。
#          #search-paths:
#          # git用户名
#          #username:
#          # git密码
#          #password:
#        native:
#          # 不指定路径的话，默认搜索 resources 目录，斜杠要用Linux的目录的方式，不能用反斜杠，否则找不到路径。
#          search-locations: E:/IdeaPro/SpringCloudDemo/configServer/src/main/resources/

eureka:
  instance:
    hostname: localhost
    # 表示eureka client间隔多久去拉取服务注册信息，默认为30秒，如果要迅速获取服务注册状态，可以缩小该值
    lease-renewal-interval-in-seconds: 15
    # 表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。
    # 默认为90秒
    # 如果该值太大，则很可能将流量转发过去的时候，该instance已经不存活了。
    # 如果该值设置太小了，则instance则很可能因为临时的网络抖动而被摘除掉。
    # 该值至少应该大于 leaseRenewalIntervalInSeconds
    lease-expiration-duration-in-seconds: 45
    # 通过ip和端口注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:admin6@localhost:9100/eureka/,http://admin:admin6@localhost:9200/eureka/,http://admin:admin6@localhost:9300/eureka/
