server:
  port: 9005
spring:
  redis:
    cluster:
      nodes:
      - 172.16.1.103:6379
      - 172.16.1.199:6379
      - 172.16.1.136:6379
      - 172.16.1.174:6379
      - 172.16.1.127:6379
      - 172.16.1.150:6379
      max-redirects: 3
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
    timeout: 60000ms
    database: 0